# Generated by Django 6.0.5 on 2026-05-21 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universidad', models.CharField(default='Universidad de Panamá', max_length=200)),
                ('carrera', models.CharField(max_length=200)),
                ('titulo_obtenido', models.CharField(max_length=200)),
                ('anio_graduacion', models.PositiveIntegerField()),
                ('indice_academico', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estado_validacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('egresado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_record', to='profiles.egresadoprofile')),
            ],
            options={
                'verbose_name': 'Historial Académico',
                'verbose_name_plural': 'Historiales Académicos',
            },
        ),
    ]
