# Generated by Django 6.0.5 on 2026-05-21 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('salario_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modalidad', models.CharField(choices=[('REMOTO', 'Remoto'), ('PRESENCIAL', 'Presencial'), ('HIBRIDO', 'Híbrido')], max_length=20)),
                ('ubicacion', models.CharField(default='Panamá', max_length=200)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADA', 'Aprobada'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='profiles.empresaprofile')),
            ],
            options={
                'verbose_name': 'Oferta Laboral',
                'verbose_name_plural': 'Ofertas Laborales',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('egresado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.egresadoprofile')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joboffer')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'unique_together': {('job_offer', 'egresado')},
            },
        ),
    ]
